Adding Index Generation for Relationships and Standalone Fields
nytm/sugarcli-nyt pull request #8
Opened 2016-09-22 23:32 UTC by jcora-nyt

I'll send you guys the _composer.json_ file to use to test this feature locally.

2016-09-23 11:41 UTC, ashutoshsinghnyt commented on res/code_templates/index/custom/Extension/modules/__module__/Ext/Vardefs/idx___index__.php.twig
> +    'fields' => array(
We may want to define type for some of the indices.

2016-09-23 11:42 UTC, ashutoshsinghnyt commented on res/code_templates/relationship-right/custom/Extension/modules/__module__/Ext/Vardefs/idx_for___relationship-right__.php.twig
> +$dictionary["{{ moduleBean }}"]["indices"][] = array(
* Should we consider ability to add length for an index as optional parameter from CLI tool or it should be a manual job by tweaking the index definition file?
* Tried to define index on multiple columns but the command is putting encoded string in the fields key of index definition.

2016-09-23 11:42 UTC, ashutoshsinghnyt requested changes

2016-09-23 15:29 UTC, jcora-nyt commented on res/code_templates/index/custom/Extension/modules/__module__/Ext/Vardefs/idx___index__.php.twig
> +    'fields' => array(
I'm not sure what you mean. There is only one index type.

2016-09-23 15:32 UTC, jcora-nyt commented on res/code_templates/relationship-right/custom/Extension/modules/__module__/Ext/Vardefs/idx_for___relationship-right__.php.twig
> +$dictionary["{{ moduleBean }}"]["indices"][] = array(
In Sugar 7.7 I don't see length as an available option for a index. Regardless, I see it as being a manually set similar to change varchar length for fields.

2016-09-23 15:59 UTC, jcora-nyt commented on res/code_templates/relationship-right/custom/Extension/modules/__module__/Ext/Vardefs/idx_for___relationship-right__.php.twig
> +$dictionary["{{ moduleBean }}"]["indices"][] = array(
I see the encoding issue you mentioned (weird), and I'll get a fix in for it.

2016-09-23 16:47 UTC, jcora-nyt commented
@ashutoshsinghnyt: Encoding problem for multiples fields was fixed. Please continue the review.

2016-09-27 13:28 UTC, ashutoshsinghnyt commented on res/code_templates/index/custom/Extension/modules/__module__/Ext/Vardefs/idx___index__.php.twig
> +    'fields' => array(
Other types are  **_Primary_** and _**Unique**_.

2016-09-27 13:55 UTC, ashutoshsinghnyt commented
Looks Good, Merging.

2016-09-27 13:56 UTC, merged