commented the code for elastic search from varchar field template
nytm/sugarcli-nyt pull request #9
Opened 2017-01-03 16:34 UTC by harjeet-nyt

2017-01-03 16:36 UTC, harjeet-nyt commented
@ash-nyt @jcora-nyt Please review the change to make unified_search by default false. I have commented all the lines related to elastic search instead of making it "false".

2017-01-04 23:37 UTC, ash-nyt requested changes

2017-01-04 23:37 UTC, ash-nyt commented on res/code_templates/field/varchar/custom/Extension/modules/__module__/Ext/Vardefs/sugarfield___field__.php.twig
> +    //'unified_search' => false,
Why did you comment this out?

2017-01-04 23:37 UTC, ash-nyt commented on res/code_templates/field/varchar/custom/Extension/modules/__module__/Ext/Vardefs/sugarfield___field__.php.twig
> +    //    'searchable' => true,
Also why is this true?

2017-01-05 07:42 UTC, harjeet-nyt commented on res/code_templates/field/varchar/custom/Extension/modules/__module__/Ext/Vardefs/sugarfield___field__.php.twig
> +    //'unified_search' => false,
I commented the lines as I thought if we need to enable the search feature we can uncomment the lines.

2017-01-05 07:43 UTC, harjeet-nyt commented on res/code_templates/field/varchar/custom/Extension/modules/__module__/Ext/Vardefs/sugarfield___field__.php.twig
> +    //    'searchable' => true,
It was already there for search feature enabled fields. If we do not want to enable search feature we can remove these lines altogether. That is why I commented them.

2017-01-11 15:33 UTC, jcora-nyt commented on res/code_templates/field/varchar/custom/Extension/modules/__module__/Ext/Vardefs/sugarfield___field__.php.twig
> +    //    'searchable' => true,
@harjeet-nyt, remove the commented lines except for `unified_search` that the value should be false by default.

2017-01-11 15:42 UTC, harjeet-nyt commented on res/code_templates/field/varchar/custom/Extension/modules/__module__/Ext/Vardefs/sugarfield___field__.php.twig
> +    //    'searchable' => true,
@jcora-nyt, made the change.

2017-01-11 15:43 UTC, jcora-nyt approved these changes
Looks good. Merging.

2017-01-11 15:43 UTC, merged